create_table = """
        CREATE TABLE IF NOT EXISTS ACTIVITIES(
        ID INTEGER PRIMARY KEY     AUTOINCREMENT,
        ACTIVITY  TEXT    NOT NULL,
        HASHTAGS  TEXT    NOT NULL,
        PLACE  TEXT    NOT NULL,
        DATE  TEXT    NOT NULL,
        TIMENEEDED  TEXT    NOT NULL,
        PEOPLENEEDED  TEXT    NOT NULL,
        CONTACT  TEXT    DEFAULT 'NONE',
        PRICE  TEXT    NOT NULL,
        DESCRIPTION  TEXT    NOT NULL,
        CREATEDAT  TEXT    NOT NULL,
        CREATEDBY  TEXT    NOT NULL,
        ISAPPROVED BOOLEAN DEFAULT 0,
        ISVALID BOOLEAN DEFAULT 1
        );
        """